parameters:
#    paginator.example.class: Jmardz\PaginatorBundle\Example

services:
#    paginator.example:
#        class: %paginator.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
